title: "Ko Labssssss"
description: 
  Yale School of Public Health\
  New Haven, CT, USA
baseurl: "/site"
url: "https://ko-laboratory.github.io/"

# Build settings
theme: minima

# Navigation
header_pages:
  - research.md
  - team.md
  - publications.md
  - contact.md

# Other configurations
markdown: kramdown
highlighter: rouge