title: "Ko Lab"
description: >
  Yale School of Public Health
  New Haven, CT, USA
baseurl: "/site"
url: "https://ko-laboratory.github.io/"

# Build settings
theme: minima

# Navigation
header_pages:
  - research.md
  - team.md
  - publications.md
  - contact.md

# Other configurations
markdown: kramdown
highlighter: rouge
sass:
  style: compressed # or nested, expanded, or compact depending on your preference