title: "Ko Lab"
description: 
  Laboratory of Epidemiology and Public Health
  Yale School of Public Health
  New Haven, CT, USA
baseurl: "/site" # the subpath of your site, e.g. /blog
url: "https://ko-laboratory.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima

# Navigation
header_pages:
  - index.md
  - research.md
  - team.md
  - publications.md
  - contact.md

# Other configurations
markdown: kramdown
highlighter: rouge