title: "Ko Laboratory"
description: 
baseurl: "/site"
url: "https://ko-laboratory.github.io/"

# Build settings
theme: minima

# Navigation
header_pages:
  - research.md
  - team.md
  - publications.md
  - contact.md

# Other configurations
markdown: kramdown
highlighter: rouge